import "./globals.css";
import { Inter } from "next/font/google";

import {
  Background,
  CompanyLogo,
  ServiceWorkerComponent,
  WebSocketComponent,
} from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={inter.className}>
        <CompanyLogo />
        <ServiceWorkerComponent />
        <WebSocketComponent />
        <Background />
        {children}
      </body>
    </html>
  );
}
